name: vhack_client
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  file_picker: ^5.3.3
  image_picker: ^1.0.5
  cupertino_icons: ^1.0.2
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  fl_chart: ^0.60.0 
  timeline_tile: ^2.0.0
  provider: ^6.0.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  intl: ^0.18.0
  sleek_circular_slider: ^2.0.1
  percent_indicator: ^3.0.1
  cached_network_image: ^3.3.1
  grouped_list: ^5.1.2
  smooth_page_indicator: ^1.1.0
  google_maps_flutter: ^2.5.0
  flutter_config: ^2.0.2
  flutter_polyline_points: ^2.0.0
  flutter_colorpicker: ^1.0.3 
  flutter_svg: ^2.0.6
  dropdown_button2: ^2.3.9
  date_picker_plus: ^3.0.0
  date_picker_timeline: ^1.2.5
  lottie: ^2.6.0
  flutter_gif: ^0.0.4
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^4.2.1
  custom_info_window: ^1.0.1
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  flutter_slidable: ^3.1.0
  dartz: ^0.10.1
  uuid: ^4.0.0
  tflite: ^1.1.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  flutter_launcher_icons: ^0.13.1
  simple_waveform_progressbar: ^0.0.3
  envied: ^0.5.4+1

  
  



 






dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/riserescuelogo.png
    - assets/DementiCare.png
    - assets/bacterial.png
    - assets/image.jpg
    - assets/resumegambar.jpg
    - assets/feature/Analyze Disease icon.svg
    - assets/feature/Chatbot icon.svg
    - assets/feature/Machines icon.svg
    - assets/feature/Pest icon.svg
    - assets/feature/Services icon.svg
    - assets/feature/Team icon.svg
    - assets/AirHumidity.png
    - assets/job/fertilizer.svg
    - assets/job/harvest.svg
    - assets/job/irrigation.svg
    - assets/job/spray.svg
    - assets/job/seeding.svg
    - assets/job/custom.svg
    - assets/job/exp/fieldreport.svg
    - assets/job/exp/FinanceTask.svg
    - assets/job/exp/sampling.svg
    - assets/job/exp/seddlingtreatement.svg
    - assets/job/exp/soilpreparation.svg
    - assets/job/exp/trial.svg
    - assets/paddy.svg
    - assets/Crop Vision.svg
    - assets/PaddyX.svg
    - assets/weather/cloud-sun.svg
    - assets/weather/clouds-sun.svg
    - assets/weather/hot-sun.svg
    - assets/weather/rain-sun.svg
    - assets/weather/rain.svg
    - assets/weather/sun.svg
    - assets/weather/thunder.svg
    - assets/weather/thunderstom.svg
    - assets/weather/wind.svg
    - assets/loading/loading-weather.json
    - assets/Humidity1.svg
    - assets/Temperature.svg
    - assets/gif/tractorMachines.gif
    - assets/userprofilewallpaper.jpg
    - assets/logo.png
    - assets/sosmed/facebook.svg
    - assets/sosmed/instagram.svg
    - assets/integration/crop_integration.png
    - assets/field/mouse.png
    - assets/field/tempsensor.png
    - assets/integration/tutorial/seed.png
    - assets/integration/tutorial/soil.png
    - assets/integration/tutorial/irrigation.png
    - assets/integration/tutorial/soiltemp.png
    - assets/integration/tutorial/fertilizing.png
    - assets/integration/tutorial/monitorpaddy.jpeg
    - assets/integration/tutorial/monitorpest.png
    - assets/integration/tutorial/harvest.jpg
    - assets/integration/tuto.svg
    - assets/welcome/welcome.png
    - assets/field/pestdetector.png
    - assets/field/soiltempdetector.png
    - assets/field/paddyXbg.png
    - assets/weather/weather.svg
    - assets/feature/weather_feature.svg
    - assets/ai/labels.txt
    - assets/ai/model.tflite
   
flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/logo.png"
  min_sdk_android: 21
  remove_aplha_ios: true













  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
